version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    user: root
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data_redis:/data

  postgres:
    image: postgres:13.3
    user: root
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data_pg:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    user: root
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data_admin:/var/lib/pgadmin