global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: exporter
    static_configs:
      - targets: ["exporter:9101"]

  - job_name: worker
    static_configs:
      - targets: ["worker:9965"]